### ISSUE TITLE
New views when using memory viewer [Feature Request]

### ISSUE THREAD

**Issue by theboy181** [aldelaro5/Dolphin-memory-engine#31] opened 2018-04-21 14:29 UTC
Would it be possible to add new views to the memory viewer? EXAMPLE: I would like to see break lines between 4 bytes, so its easier to review.

![image](https://user-images.githubusercontent.com/9299743/39085333-c757d830-4535-11e8-8fce-d41c9a05a008.png)

**Comment by aldelaro5** [comment] 2018-04-22 00:25
I agree that this could be nice and I did intended to add it, but idk WHEN I will do it, maybe 0.5 because I plan to add persistent settings in that release so having separators like those in Cheat Engine could be possible to set and save.

In fact, I probably will do them CE style, they were nice.

**Comment by theboy181** [comment] 2018-04-22 00:53
if you are planning on taking a page from cheat engine, can I encourage you to also allow the space bar to lock the vales when you have a group selected? 

I started looking into using CE with Dolphin and I wish I could have CE identify the RDRAM automatically like this program.

**Comment by aldelaro5** [comment] 2018-04-22 01:08
Multi edit and multi lock is defintetly somethign I want to do because it's usefull when you try to find an address out of like 50 and you lock groups of them until you find the one that does an effect.

Btw, identifying MEM1 isn't enough, you have to completely recalculate the address so you get the vaddress, the pointers has to work in big endian AND with the gc/wii layout, etc....  It's not the only problem CE had that this project attempts to fix.  Also, CE is much harder to maintain imo and to do what I am doing you would have to maintain a fork which I am not found of doing, I actually like this codebase much more than the CE one which I had many issues with it.

So yeah, I want to keep what was good about CE, but make it work into dolphin.

**Comment by theboy181** [comment] 2018-04-22 03:25
This program should be packed with Dolphin. its really good.

**Comment by aldelaro5** [comment] 2018-04-22 04:29
About that.....it's much more complicated which is why I decided against it at first.

The problem is to do what I am doing integrated to dolphin, I would have to insert hooks in VERY performance critial spot (functions that are called milions of times per second) and use them A TON.  For example, the viewer needs me to get 24mb (add 60 for mem2) of ram every 100ms, the address list also as well as the scan result list also needs constant refreshing which there's no other way to do this, but to poll the ram constantly.  

Inside dolphin, that would be really decreasing the performance, but from an external process, it's very trivial to do and I can do it constantly without having dolphin slow down, but it comes at a price: I cannot access dolphin's internal state, only observe it from outside which happens to be enough to what I want.

I might try in the very far future to attempt it, but I do not expect good results.

**Comment by aldelaro5** [comment] 2018-04-22 10:09
That won't happen because I am the sole maintainer of this and it goes a bit beyond the scope of dolphin, but the reality is they know about it, in fact, I know the main tester uses it to debug some weird game bugs so it's nice.

So I am okay if it's separate for now, this is a more advanced and optrimised for mass searching ram search tbh.

**Comment by theboy181** [comment] 2018-04-22 17:02
If you are interested I started a Discord on Memory hacking for Dolphin. If you have the idle time it would be nice to have you around.

**Comment by aldelaro5** [comment] 2019-03-24 04:01
as of 9e5ed0ec337c469b855b56fb259c142768177b58, customable bytes separators are implemented as well as multiselect with copy (works only one memory view at a time with the mouse, but I think I can get extended selection with the keyboard easily).

Multilock is complicated, so honestly, it's better to just add an array of bytes which to be honest, I could very well do with a right click in a multiselection, it would add the array with the correct length which you would then lock. Multiedit however, that can be done, but I will put a small prompt that will support both decimal and hex because the CE one was VERY dumb to only support decimal.

So before I close this issue, here's what's left:

- Implement multiedit over a selection using a context menu item
- Implement Add address as a context menu item for right clicking on any address
- Implement Add bytes array as a context menu over a multiselect
- Implement selection with the shift key
- ATTEMPT (no idea if this can be easily be done) selection across views using the mouse. The reason this seems complicated is because I have to scroll when the mouse is lower than the viewer so I have no idea if it can be doable and be usable.

**Comment by aldelaro5** [comment] 2019-03-29 06:56
Everything is done as of 30e3264d7bea6b72e8dc3d0a8422f41c1be0f768 except the selection on mouse through scrolling, but I think as far as this issue goes, I am okay to close it now.  I'll maybe attempt in a further pr for the selection through mouse.

**Closed by aldelaro5** 2019-03-29 06:56 UTC
Labels: feature request
