### ISSUE TITLE
Merge Dolphin Memory Engine into Dolphin

### ISSUE THREAD

**Issue by NicholasMoser** [aldelaro5/Dolphin-memory-engine#53] opened 2020-12-02 21:29 UTC
[In a PR I opened](https://github.com/aldelaro5/Dolphin-memory-engine/pull/52#issuecomment-737447160), @aldelaro5 mentioned it would be ideal to merge this within Dolphin. I agree as it would provide a number of benefits:
- More visibility
- Direct access to MEM1 and MEM2
- Support on all Dolphin supported platforms
- Guaranteed support on the latest Dolphin versions

It would effectively invalidate all of the following issues and PRs:
- [MEM2 Wii only RAM not found even when playing Wii games](https://github.com/aldelaro5/Dolphin-memory-engine/issues/46) since this is an issue relating to finding where Windows placed MEM2 in memory
- [Doesn't work with renamed executables](https://github.com/aldelaro5/Dolphin-memory-engine/issues/42) since it would run within the Dolphin executable.
- ["Cannot hook to Dolphin, the process is running, but no emulation has been started" error](https://github.com/aldelaro5/Dolphin-memory-engine/issues/35) since it would no longer need to hook to Dolphin
- [MacOS support](https://github.com/aldelaro5/Dolphin-memory-engine/pull/50) since it would piggy-back Dolphin MacOS support.

I intend to look into doing this myself. Please feel free to comment if you are interested or have any thoughts regarding this.

**Comment by heyitsdeity** [comment] 2020-12-27 17:14
Aldelaro has stated (at least on Twitter, I know for sure in the Animal Crossing Modding discord server) that they have largely abandoned this project, so I'd love to see this merged and developed further by the Dolphin dev team.

**Comment by aldelaro5** [comment] 2020-12-27 18:14
> Aldelaro has stated (I believe on Twitter, I know for sure in the Animal Crossing Modding discord server) that they have largely abandoned this project, so I'd love to see this merged and developed further by the Dolphin dev team.

Just to clarify: abandoning is not the correct word it's more "on hold for an undefined period of time" because I can't feasibly maintain it at the moment and I still love this project, but there's just no way I can continue it at the moment and likely not for a while (we might be talking years here, idk). I do welcome someone else to do the merging work I actually HAD PLANNED to do before Bug Fables happened though.

**Comment by NicholasMoser** [comment] 2021-01-05 00:43
Another reason it may be worth merging this directly into Dolphin is that MEM1 and MEM2 are now configurable[1], which Dolphin Memory Engine will not work with since it expects them to each be a specific size.

[1] https://github.com/dolphin-emu/dolphin/pull/8722

**Comment by pyorot** [comment] 2021-02-11 18:24
Hey, just dropping a note that I think this is high-priority for various glitch-hunting communities, if only to resolve the requirement of using 5.0-13333 or earlier (betas). What's the progress, or the strategy for reporting this to Dolphin's team?

**Comment by aldelaro5** [comment] 2021-02-23 08:53
> Hey, just dropping a note that I think this is high-priority for various glitch-hunting communities, if only to resolve the requirement of using 5.0-13333 or earlier (betas). What's the progress, or the strategy for reporting this to Dolphin's team?

VERY sorry for the late reply, I have been busy lately, but to answer, you can't report it as an issue because the problem isn't on their side, it's a problem relating to DME that you have to adapt the backend to support these versions. I would NORMALLY have done so asap, but ever since 2020, I had other projects I put higher priorities. I am however debating to come back to this project to solve ONLY the very very urgent issues and make a release so people can at least work, but I don't expect this to happen soon, maybe in the coming weeks, we'll see.

**Comment by NicholasMoser** [comment] 2021-02-24 00:16
@pyorot can you elaborate on this issue of Dolphin 5.0-13333? I'm not sure what issue you're specifically talking about.

Do you mean https://github.com/aldelaro5/Dolphin-memory-engine/issues/46 ?

I have a fix open in a PR here if you'd like to test it: https://github.com/aldelaro5/Dolphin-memory-engine/pull/52

**Comment by NicholasMoser** [comment] 2021-02-24 00:17
Like @aldelaro5 I've also been busy, and have put investigating this issue on the backburner since I have a workaround for https://github.com/aldelaro5/Dolphin-memory-engine/issues/46 found at https://github.com/aldelaro5/Dolphin-memory-engine/pull/52

Aldelaro5 if you do have any interest in coming back to this let me know, I'm willing to work with you on it if you'd like.

**Comment by aldelaro5** [comment] 2021-02-27 00:19
Currently, it's looking likely I will be forced to come back to this for a couple of days to extinguishes the few fires like #46 which #52 seems to address as well as #35 and since i now have a functional mac os vm, I could try to check #50 but no promise on this one. This is ONLY going to be a hotfix release (or I guess feature if I can get the mac stuff to work).

@NicholasMoser unfortunately, merging dolphin with this is something I can't do now, I can only come back to resolve the emergencies people are having so they can at least work (because my god this project is used WAY MORE than I expected so it not working is stalling a lot of people), but I will be looking into the issues I listed. Your help is appreciated for these, but unfortunately, the merge dolphin part will have to wait a while for me when I do decide to come back.

**Comment by pyorot** [comment] 2021-03-01 16:25
Cheers, guys. @NicholasMoser sorry for being unclear, 5.0-13333 is the last beta that works with MEM2, which is indeed issue #46 and pull #52. I can't test them myself since I don't actively use a C++ environment atm. These fixes would be much appreciated, but I was also considering how I might advocate for the Dolphin dev team to pick this project up as something to merge themselves.

**Comment by Tragicus** [comment] 2021-12-12 22:21
Hi ! It is probably a bit late to appear, but I have just done the merging (after unsurprisingly not being able to make DME work on Mac). It still requires some cleaning and testing, but it runs. Do you think I should publish my changes somewhere once I am happy with the result?

**Comment by aminoa** [comment] 2023-01-16 02:49
@Tragicus you can open up a draft PR on the dolphin repo and push your current changes

**Comment by dreamsyntax** [comment] 2023-10-31 19:50
Ultimately the Dolphin team decided against this. The memory tab now has near feature parity, so I'm closing this.
https://github.com/dolphin-emu/dolphin/pull/11588#issuecomment-1437658866

**Closed by dreamsyntax** 2023-10-31 19:50 UTC
