### ISSUE TITLE
Very poor performance on newer hardware

### ISSUE THREAD

**Issue by StackOverflow0x** [aldelaro5/Dolphin-memory-engine#67] opened 2023-09-09 06:40 UTC
I used to run Dolphin Memory Engine quite well on my old system which had an i5-2500k CPU. Since I upgraded to a i7-13700K, and hooked to Dolphin 5.0 18281, performance in the memory engine has been really poor. The UI is very sluggish and unresponsive. This never happened on my older hardware. Has anyone else had these issues? I can't really use this tool when it's in a barely working state like this.

**Comment by jonko0493** [comment] 2023-10-01 09:55
This seems to be a problem unique to 0.6.0; downgrading to 0.5.1 fixed this issue for me.

**Comment by jonko0493** [comment] 2023-10-01 10:34
I'm also having this issue on newer hardware. It's hard for me to bisect the issue as 0.5.1 does not connect to Dolphin and 0.5.0 has the MEM2 connection bug.

https://github.com/aldelaro5/Dolphin-memory-engine/commit/46e1f40232273960dc31f6eb122b75fd8afa3ba2 seems to be the commit that introduced it, but it's hard to say for sure due to the above reasons.

**Comment by aldelaro5** [comment] 2023-10-01 13:00
I am really not sure myself. If anything, I would expect the ARAM to impact everyone (cause it just means it probes more memory), but it only impacts older hardware?

If it truly is the ARAM, you could enable MMU to make it not detect it, but if that doesn't solve it, I truly have no idea....

**Comment by StackOverflow0x** [comment] 2023-10-05 02:20
Would this MMU thing help in my case on the latest version? My issue is this is happening on newer hardware. I don't remember what version I used on my older hardware, but it seems like the right combination then and the wrong combination now.

**Comment by aldelaro5** [comment] 2023-10-05 12:12
Tbf, enabling MMU especially if you care about memory accuracy (such as memory related crashes or behaviors) is generally something I recommend. I think in older versions of dolphin, it used to be much more demanding, but nowadays, I don't think it's that much of a diff, my info are very outdated though.

The issue is DME, because it basically does a hack to get the thing to work in the first place, the ARAM (which only some games uses via a nintendo provided SDK library) can only be probed if MMU is disabled in dolphin. So I was suggesting if the ARAM probing is the issue, you could try to enable MMU to see if it fixes the problem because besides that, I don't recall significant changes I did on the latest version.

If that doesn't work, I truly have no idea.

**Comment by StackOverflow0x** [comment] 2023-10-09 02:58
I see. The description still says OFF = Slow. But it seemed okay in the brief moment I tested with it on. And with it on, Dolphin Memory Engine runs just as snappy as it used to. I could keep MMU on when I need to use this tool, as a workaround.

**Comment by aldelaro5** [comment] 2023-10-09 03:28
Interesting, another thing you could try btw: you can increase the refresh timers in the settings so it polls less frequently

Honestly, the way I did this is not efficient at all, but it has still worked enough, it's just interesting you get this on newer hardware...

**Comment by StackOverflow0x** [comment] 2023-10-13 05:28
I had tried changing the refresh timer before and it didn't help much. The UI is still very unresponsive and overall very slow. Either I had MMU on when I was on older hardware, or it's strangely a newer hardware thing.

**Comment by TurtleMan64** [comment] 2023-10-23 22:16
I am having this problem as well after switching to a new computer with Window 11 and better hardware.

On 0.6.0 the UI is very unresponsive once hooking into Dolphin, even on a new project with no watches/scans.

I am currently working around it by increasing the Memory viewer update timer to 10,000 ms. The other timers seem fine to leave at 100 ms.

**Comment by dreamsyntax** [comment] 2023-10-31 19:48
Someone mentioned on discord the issue is related to whether DME or Dolphin is opened first and when the hook happens. I will be investigating this.

> Yonder:
> The program lags (presumbly due to the timers that watch for changes in memory and if dolphin opens running in the background). The exception is it does not lag if it is opened before any dolphin process is launched, then is hooked to dolphin only when a game is running.
>
> I tried following the code for awhile. I initially thought it was lagging because of the initial hook it attemps when first opening (ie. it hooks before the opening animation starts and therefore causes lag cause of interrupted animation). So I commented out that call but not only did it not fix it, it caused lots of issues so I presume that initial hook is required for initialization

**Comment by dreamsyntax** [comment] 2023-11-01 05:59
Can someone experiencing this issue please try the Qt 6 build?

Scroll down to Artifacts on the Summary page, then pick windows (Release) if on Windows.
https://github.com/aldelaro5/Dolphin-memory-engine/actions/runs/6716216989?pr=71
![image](https://github.com/aldelaro5/Dolphin-memory-engine/assets/14857235/c4af5166-01a4-4d62-a918-d838beb7e94e)

I was able to constantly reproduce this, but using my wip build above it seems to be resolved for some reason.

**Comment by dreamsyntax** [comment] 2023-11-01 07:31
Someone else has tried this build and confirmed it resolved the issue for them. Waiting for more feedback and my own usage.

**Comment by StackOverflow0x** [comment] 2023-11-02 04:12
I can confirm that Windows build runs much better now. Even with MMU toggled off, the tool is just as responsive.

**Comment by dreamsyntax** [comment] 2023-11-02 08:28
Did some more tests.
- 0.5.0
- 0.5.1
- 0.6.0
- Qt6.5 PR Build

Overall, I can still get all builds to lag on Windows with the memory viewer open while having a fairly large DMW loaded.
We can probably optimize, but I think this confirms it was not caused by 0.6.0.
I'm thinking Windows internals updates caused this. If updating to Qt 6 brings it back to acceptable levels, that's awesome. There will be a release shortly once we wrap up the outstanding PRs and do one final Qt 5 release, for those who will be left behind the Qt 6 dependency increase (Win 7, Win 8).

Unless someone else here has reproduce the lagging on Linux, because I can't.

**Comment by dreamsyntax** [comment] 2023-11-04 03:18
Closing this for now. If the issue occurs again on v0.8.0 please re-open or open a new issue.

**Closed by dreamsyntax** 2023-11-04 03:18 UTC
Labels: bug
