### ISSUE TITLE
Ship Qt 5 libraries on linux

### ISSUE THREAD

**Issue by Henrik0x7F** [aldelaro5/Dolphin-memory-engine#32] opened 2018-05-12 11:52 UTC
The program seems to require newer Qt libraries than the ones installed on Ubuntu 16.04. Shipping the required *.so files in the zip would remove the need to install the whole ~2Gb Qt SDK.

**Comment by BPopcorn** [comment] 2018-05-13 11:17
It seems the problem goes a bit deeper. In order to use shipped libraries the folder containing them has to be added to LD_LIBRARY_PATH before the program is launched. The problem when you run `setcap` on the executable LD_LIBRARY_PATH is ignored for security reasons. This also applies for running the program as super user. So it's impossible run the program...

**Comment by aldelaro5** [comment] 2018-05-13 11:39
So, does that mean that even if you had a package of the Qt libs, it wouldn't work?

That would be odd and weird, there has to be way to have the required privilege without root being required...

**Comment by BPopcorn** [comment] 2018-05-13 11:46
It's only usable if the Qt libs are installed in the system directories. When libs are in another directory they need to be manually added to LD_LIBRARY_PATH. For example with a start.sh:
```
export LD_LIBRARY_PATH=/media/QT/5.10.1/gcc_64/lib
./Dolphin-memory-engine
```
The problem is once the program is run as sudo or permissions are modified with `setcap` LD_LIBRARY_PATH is ignored, always. That means either a ppa is required or the required Qt version has to be set to something preinstalled on ubuntu 16.04. My current workaround is to disable ptrace scope globally with `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`. But this is kinda unsafe and also requires root access.

**Comment by BPopcorn** [comment] 2018-05-13 13:03
Have a look at [posix_spawn](https://linux.die.net/man/3/posix_spawn). If you launch dolphin within the program you don't need any special permissions to access it's memory.

**Comment by aldelaro5** [comment] 2018-05-13 19:47
Ok so essentially, this means I can't do much for this issue, the setcap is somethign I relaised I needed after to tell after someone had a permission issues I didn't have.  You coudl try without the setcap and if it can't hook to dolphin then you need it.

But yeah, I NEED the permissions setcap gives me so that I can't chnage it.  As for the libs, it's even less reason for me to include them because they need to be properly installed which I rather let distributiuon maintainers or PPA do this part, Windows however, I have no choice so I give the dll.

**Comment by aldelaro5** [comment] 2019-03-01 09:21
As with #34 , I won't be supporting an older version of Qt because the readability benefits is big enough for it. As I said, use a PPA or something, a long time has passed since this issue was opened so newer Qt versions should become more accessible, but yeah, I would definitely check for a PPA (I think the travis CI works with a PPA for now so I know it can work).  For now, I am closing this as I am definitely not going to ship the libs with the executable as discussed.

**Closed by aldelaro5** 2019-03-01 09:21 UTC
